### PR TITLE
Watchers notifications

### PR DESCRIPTION
**Pull request by Safi-Ullah**
## Issue:
https://github.com/fenske/devskills-app/issues/217

## What New: 
- An option for the user to "watch" the candidate which effectively signs them up for email updates for each state change for that candidate.
- Whenever a candidate changes its state a corresponding email is sent to all watchers.
- Whenever a user invites a candidate, they automatically become the watcher of that candidate.

### CODE REVIEW

**Comment by fenske** [comment]
NOTE: I'll need to enable emails on the preview env before we can test it.

**Comment by fenske** [comment]
> NOTE: I'll need to enable emails on the preview env before we can test it.

@Safi-Ullah Just verified that emails work (and also realized that you can't see it anyway 😅).

But you can test by making sure that the corresponding doc appears in the `mail` collection.

I'll be able to test & code review this PR later today.

**Comment by fenske** [comment]
@Safi-Ullah One thing I noticed already though is that I believe we should add the "Watch this candidate" toggle to the "Invite candidate" slideover as per: 

CleanShot 2021-05-27 at 10 20 58@2x

Otherwise, users won't have an option to opt out on the spot.

**Comment by fenske** [comment]
Also, noticed a new composite index was required, so creating it.

**Comment by Safi-Ullah** [comment]
> * [ ]  @Safi-Ullah One thing I noticed already though is that I believe we should add the "Watch this candidate" toggle to the "Invite candidate" slideover as per:
> 
> CleanShot 2021-05-27 at 10 20 58@2x
> 
> Otherwise, users won't have an option to opt out on the spot.

There it can be used only to opt out while sending a challenge, but if at some other point user wants to, then they'll have to do so from the `Candidate Overview` slideover. So, should I add the slider in both slideovers..?

**Comment by fenske** [comment]
> So, should I add the slider in both slideovers..?

Yeap. Only in the case of the "Invite candidate" one, has to be toggled on by default.

A typical scenario for this is when say someone from the hiring team invited a candidate on behalf of someone else, so they're not interested in following the candidate's progress. So they un-toggle it on the spot.

**Comment by fenske** [comment]
HEADS-UP. To make the state changes work in Preview, the BASE_URL also needs to change in Vercel.

I've done that, but for some reason, it didn't make the state changes work. 🤷 Will need to look into it separately later today when I review the PR.

**Comment by fenske** [comment]
## UI test results

@Safi-Ullah I've done some UI testing. Please check out the findings below. 

### Bug

- [ ] IS FIXED?

Emails get sent on no state change. Shouldn't happen.

CleanShot 2021-05-27 at 16 50 53@2x

To reproduce just create and close PR/issue.

### Suggestion for email copy improvement

- [ ] IS FIXED?

1. Let's reframe the email subject to "A new candidate state change for ${name ?? username}"
2. In the email copy, let's say "candidate state change" rather than "candidate change" as originally proposed.
3. Let's remove the duplicated dot at the end of the sentence.


CleanShot 2021-05-27 at 16 35 48@2x

**Pull request merged**
