### PR TITLE
[feat]: Retrieve sorted challenges list

### PR DESCRIPTION
**Pull request by Safi-Ullah**
## What's done
- Sorted alphabetically by profile.
- Within each profile, alphabetically by challenge name.

## Additional info:
The composite index of profile and name field of challenges collection needs to be formed.

### CODE REVIEW

**Comment by fenske** [comment]
@Safi-Ullah Thanks for pointing out that a new index has to be created.

Also, this PR has [WIP] in the title. Does this mean you'll be adding more changes to it?

**Comment by Safi-Ullah** [comment]
> Also, this PR has [WIP] in the title. Does this mean you'll be adding more changes to it?

I just wanted to ask whether the pinned challenges need to be sorted or not.

**Comment by fenske** [comment]
> > Also, this PR has [WIP] in the title. Does this mean you'll be adding more changes to it?
> 
> I just wanted to ask whether the pinned challenges need to be sorted or not.

Good that you raised it. Right now the order is kinda funky (i.e. when first adding a new challenge via `mutate` it adds it as the first item. 

But after it fetches the list via SWR, the order of the pinned challenges might be completely different, which makes them "jump at random".

Ideally, the order in which they'd been pinned should be kept.

Any ideas how to implement it?

**Comment by Safi-Ullah** [comment]
> Any ideas how to implement it?

If the pinned list was to be sorted alphabetically, then we could simply add the newly pinned item at the appropriate place in the list rather than simply adding it as the first.
But, if we want to maintain the order in which the challenges were pinned, then I'm thinking we might need to introduce a timestamp field that can help maintain the order. Any thoughts..?

**Comment by fenske** [comment]
Makes sense what you say. Let's keep it simple this time. No changes to the pinned list.

**Comment by Safi-Ullah** [comment]
Yeah, sure...then I think the PR is finalized from my end.

**Pull request merged**
