### PR TITLE
#229 : Fix the bug with missing id.

### PR DESCRIPTION
**Pull request by fenske**

### CODE REVIEW

**Comment by fenske** [comment]
@Safi-Ullah check this out. I missed this too. 😅


https://user-images.githubusercontent.com/1162212/123622629-c3232680-d80c-11eb-9ff5-d22295449e70.mp4

**Comment by Safi-Ullah** [comment]
> @Safi-Ullah check this out. I missed this too. 😅

🤦 ...I'll create a PR for DOM test today as well....we should really pay more attention to it.

**Comment by fenske** [comment]
Sounds good. What testing framework are you thinking of?

**Comment by Safi-Ullah** [comment]
> Sounds good. What testing framework are you thinking of?

I'm thinking of going with the `Enzyme` testing library for the DOM/rendered components manipulation.

**Comment by fenske** [comment]
> > Sounds good. What testing framework are you thinking of?
> 
> 
> 
> I'm thinking of going with the `Enzyme` testing library for the DOM/rendered components manipulation.

We use Cypress all over the DevSkills challenge library. 

Would you think you could leverage it here too, so that we preserve the tech stack integrity across the platform? 😬

**Comment by fenske** [comment]
Btw, I implied it indirectly, but feel free to create a separate ticket for setting up the e2e testing and log the dev time on it.

**Comment by Safi-Ullah** [comment]
> Btw, I implied it indirectly, but feel free to create a separate ticket for setting up the e2e testing and log the dev time on it.

sure, I'll create the ticket for this...

**Pull request merged**
